### ISSUE TITLE
Visualization+statistics

### ISSUE THREAD

**Issue by sumanthvrao** [sumanthvrao/We_R_Pythons#3]
Need to :  
1) cleaning the data , pre-processing it
2) Modeling the data.
3) Evaluate by running basic tests on it.

**Comment by sumedhpb** [comment]
[Basic+Analysis.zip](https://github.com/sumanthvrao/We_R_Pythons/files/2481169/Basic%2BAnalysis.zip)

**Comment by sumedhpb** [comment]
issue 3. basic stats and visualisation done

**Comment by sumanthvrao** [comment]
changed

**Comment by sumedhpb** [comment]
Completed
